version: "3"
services:
  webserver:
    image: muthummkdh/nginx:1.1
    container_name: muthu
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/grafana.ini:/etc/grafana/grafana.ini:ro


  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
  
  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - /home/ubuntu/blackbox.yml:/etc/blackbox_exporter/config.yml